on:
  pull_request:
    types: [opened, ready_for_review, reopened]
name: Add PR comment with instructions for review
jobs:
  addReviewInstructions:
    name: Review instructions
    runs-on: ubuntu-latest
    steps:
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            This comment was written by a bot!

            This comment should contain information for the reviewer and reviewee.

            And this is a [Link](https://github.com/marketplace/actions/create-or-update-comment) to a good resource.
          reactions: rocket