on:
  pull_request:
    types: [opened, ready_for_review, reopened]
name: Add PR comment with instructions for review
jobs:
  addReviewInstructions:
    name: Review instructions
    runs-on: ubuntu-latest
    steps:
      - name: Render template
        id: template
        uses: chuhlomin/render-template@v1.5
        with:
          template: .github/pr-comment-template.md
          vars: |
            foo: this
            bar: that
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: ${{ steps.template.outputs.result }}
          reactions: rocket