name: "Pull Request Preview Build"
on: pull_request

jobs:
  pr-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Get HEAD SHA
        run: echo "PR_SHA=$(git rev-parse HEAD)" >> $GITHUB_ENV
      - name: Verify HEAD SHA
        run: echo "PR_SHA=${PR_SHA}"
      - name: Test2
        run: echo $PR_SHA
      - name: Set env
        run: echo "GITHUB_SHA_SHORT=$(echo $PR_SHA | cut -c 1-6)" >> $GITHUB_ENV
      - name: Test
        run: echo $GITHUB_SHA_SHORT
      - name: Test Env
        run: env
